import { C } from "./themes.js";

// ─── DEFAULT CODEX SPELLS ─────────────────────────────────────────────────────
export const DEFAULT_CODEX = {
  "Language Models": [
    { title:"Deep Research Brief", description:"Extract the real picture, not the consensus.",
      spell:{ anchor:"You are a world-class research analyst and investigative journalist with deep domain expertise.", feeling:"I need a comprehensive, honest analysis of [TOPIC]. Not the surface-level consensus — the real picture, including what's contested, what's overlooked, and what the mainstream view gets wrong.", voice:"Analyze this in four sections: (1) Core Claim — the strongest version of the mainstream view. (2) Evidence For — the best supporting evidence. (3) Evidence Against — the strongest counterarguments and contradictory data. (4) Synthesis — your honest assessment of where the truth probably lies.", constraint:"Each section clearly labeled. Cite the type of evidence (studies, expert consensus, historical data) rather than specific URLs. Flag where your confidence is lower. Minimum 400 words.", permission:"If the evidence genuinely supports a contrarian conclusion, say so directly. Don't hedge to stay safe." }},
    { title:"Brand Voice Copywriter", description:"Copy that sounds like a specific brand, not like AI.",
      spell:{ anchor:"You are a senior brand copywriter with 15 years writing for premium consumer brands. You think in headlines first, emotions second, features never.", feeling:"I need copy for [BRAND/PRODUCT]. The brand is [describe brand personality]. The reader is [describe target customer and their emotional state].", voice:"Write [copy type: headline / product description / email / social caption]. The copy should make the reader feel [desired emotion], not inform them of features.", constraint:"No adjectives that describe the product as 'innovative', 'cutting-edge', 'revolutionary', or 'world-class'. No passive voice. Max [X] words. End with action, not conclusion.", permission:"If there's a more honest or unexpected angle that serves the brand better, show it alongside what I asked for." }},
    { title:"Socratic Debate Partner", description:"Pressure-test any idea without mercy.",
      spell:{ anchor:"You are a rigorous intellectual interlocutor — part philosopher, part litigator, part scientist. Your job is not to agree with me but to make my thinking stronger.", feeling:"I want to pressure-test the following idea: [STATE YOUR IDEA]. I believe it because [give your reasoning]. I want you to find every weakness, assumption, and blind spot in my argument.", voice:"Take the strongest possible opposing position. Don't strawman me — steelman my argument first, then dismantle it. Identify: (1) the weakest assumption I'm making, (2) the best counterexample to my claim, (3) an alternative framework that explains the same evidence differently.", constraint:"No agreeing with me to be polite. No hedging phrases like 'you raise a good point.' Direct, specific, intellectually rigorous.", permission:"If my idea is actually sound, say so — but only after genuinely trying to break it." }},
    { title:"Technical Concept Explainer", description:"Complex ideas made genuinely clear.",
      spell:{ anchor:"You are a brilliant science communicator who can explain anything to anyone without condescension or oversimplification. You think in analogies first.", feeling:"I need to understand [CONCEPT] at a deep level. I have [describe your background] and I'm trying to understand this because [give context].", voice:"Explain this in three layers: (1) The intuition — a concrete analogy that makes the core idea click. (2) The mechanics — how it actually works. (3) The implications — what changes once you understand this correctly.", constraint:"No jargon without immediate definition. Each layer must be self-contained. Analogies must be truly analogous, not just metaphorically similar.", permission:"If the most common explanation of this concept is subtly wrong, correct it. I want the accurate version." }},
    { title:"The Harsh Editor", description:"Cut everything that doesn't earn its place.",
      spell:{ anchor:"You are a ruthless developmental editor at a major literary press. You've edited bestsellers. You have no sentimentality about prose that isn't working.", feeling:"I'm going to share a piece of writing. I want you to edit it as if you were preparing it for publication — not for my feelings.", voice:"Read the piece and give me: (1) The single biggest structural problem. (2) The three weakest passages and exactly why. (3) What the piece is actually about versus what it thinks it's about. (4) A rewritten version of the opening paragraph.", constraint:"No praise unpaired with a specific observation. No softening language. Direct diagnosis.", permission:"If the piece needs restructuring rather than editing — say so." }},
  ],
  "Image Generation": [
    { title:"Cinematic Portrait", description:"Film-quality character portraits with mood.",
      spell:{ anchor:"Cinematic close-up portrait, 35mm film photography aesthetic", feeling:"Quiet intensity. The moment before a significant decision. Presence without performance.", voice:"Subject centered, slight downward gaze. Single practical light source from camera left, warm tungsten. Fine film grain. Shallow depth of field, background suggestion only.", constraint:"Aspect ratio 2:3. Photorealistic. No AI skin smoothing. No artificial lens flare. No blown highlights.", permission:"Reference: the intimate portrait work of Chloe Zhao and Gregory Crewdson. One unexpected compositional choice." }},
    { title:"Product Hero Shot", description:"Commercial product photography, editorial quality.",
      spell:{ anchor:"Commercial product photography, editorial quality, for a premium [PRODUCT CATEGORY]", feeling:"Considered luxury. The feeling of owning something made with genuine care. Restrained desire.", voice:"Product centered on a [surface: marble / slate / linen / concrete] surface. Studio lighting — soft diffused light from above and behind. Hero angle, 3/4 view. Colour story: [2-3 palette colours].", constraint:"Aspect ratio 4:5. Photorealistic render quality. Clean background. No props that distract from product.", permission:"One subtle environmental detail that adds narrative context without cluttering the composition." }},
    { title:"Editorial Illustration", description:"Magazine-quality conceptual illustration.",
      spell:{ anchor:"Editorial illustration for a [publication type: magazine / newspaper / book cover], [illustration style: flat graphic / painterly / collage / line art]", feeling:"Conceptual punch. The image should work as a visual metaphor for [THEME/CONCEPT]. Thought-provoking without being literal.", voice:"Strong compositional geometry. Limited, intentional palette — 3 colours maximum plus black and white. Central subject clear from 10 feet away.", constraint:"Aspect ratio 3:4. No photorealistic elements. No text.", permission:"If there's a stranger, more arresting visual approach to this concept, find it." }},
    { title:"Architectural Mood", description:"Interior or exterior spaces with atmosphere.",
      spell:{ anchor:"Architectural photography / render of a [SPACE TYPE: interior / exterior / urban / natural]", feeling:"[Choose: contemplative stillness / productive calm / dramatic grandeur / intimate warmth]. The space should feel inhabited but not busy.", voice:"Wide angle, strong perspective lines. Natural light as primary source. Golden hour or overcast for exterior. Ambient practical lighting for interior.", constraint:"Aspect ratio 16:9. Photorealistic. Human figure optional — if present, small and contextual only.", permission:"If the most interesting composition isn't the obvious one, find it." }},
  ],
};

export const CAT_COLORS = { "Language Models": C.purple, "Image Generation": C.pink };
