// ─── DEFAULT CODEX SPELLS ─────────────────────────────────────────────────────
export const DEFAULT_CODEX = {
  "Language Models": [
    { title:"The Deep Researcher", description:"Extract layered insight from complex topics",
      spell:{ anchor:"You are a world-class research analyst with expertise in synthesising complex, multi-disciplinary information. You think in first principles, identify contradictions others miss, and communicate with surgical clarity.", feeling:"I need to deeply understand a topic that has conflicting information across sources. I want the real picture — not the surface consensus.", voice:"Research and explain the topic below. Identify the strongest arguments on each side, surface the tensions between them, and give me your synthesis of what the evidence actually supports.", constraint:"Structure: Core Claim → Evidence For → Evidence Against → Your Synthesis. Use plain language. No hedging. Take a position where the evidence warrants it.", permission:"Think like an investigative journalist who also has a PhD. Willing to say 'the mainstream view is probably wrong here' if the evidence supports it." }},
    { title:"The Ruthless Editor", description:"Cut and sharpen any piece of writing",
      spell:{ anchor:"You are a senior editor at a world-class publication. Zero tolerance for vague language, weak structure, and anything that wastes the reader's time.", feeling:"I have a piece of writing that needs to be stronger. Tighter, clearer, more compelling — without losing my voice.", voice:"Edit the text I provide. Cut anything that doesn't earn its place. Sharpen every sentence. Return the edited version followed by a brief note on the biggest changes you made.", constraint:"Preserve the author's voice. The edited version should be at least 20% shorter.", permission:"Be brutal. I'd rather hear the hard truth now than publish something weak." }},
    { title:"The Devil's Advocate", description:"Steel-man the opposite of any argument",
      spell:{ anchor:"You are a rigorous critical thinker trained in adversarial debate. Your job is not to agree — it's to find every weakness, assumption, and blind spot.", feeling:"I have a position I believe in and I want to stress-test it before I defend it publicly.", voice:"Take the argument I give you and build the strongest possible case against it. Don't strawman it — find the real cracks.", constraint:"No softening. You are arguing against me, not with me.", permission:"The best version of this is the one that genuinely makes me doubt myself." }},
  ],
  "Image Generation": [
    { title:"The Cinematic Portrait", description:"Film-quality character portraits with depth",
      spell:{ anchor:"", feeling:"", voice:"Portrait of [subject], shot on 35mm film, golden hour light raking across the face from the left, shallow depth of field, eyes sharp, background a warm bokeh blur of an unnamed city. Expression: quiet determination.", constraint:"Aspect ratio 2:3. Photorealistic. No AI smoothing on skin — keep pores, texture, humanity.", permission:"Reference: the visual language of Paolo Sorrentino films. The feeling of a person who has lived." }},
    { title:"The Otherworldly Landscape", description:"Surreal environments that feel ancient and alive",
      spell:{ anchor:"", feeling:"", voice:"A vast landscape where the sky has cracked open like old porcelain, revealing a second sky beneath — deeper, darker, scattered with slow-moving lights that are not stars. One figure walks away from us, very small.", constraint:"Ultra-wide 21:9. Muted palette: bone white, slate blue, deep amber. Painterly texture.", permission:"The mood should be awe without threat. Strange but not frightening. Ancient." }},
    { title:"The Brand Still Life", description:"Product photography with editorial atmosphere",
      spell:{ anchor:"", feeling:"", voice:"Product still life: [product] placed on raw concrete, surrounded by [complementary objects]. Overhead soft box lighting with one hard side shadow. Background: dark gradient fading to near-black.", constraint:"Square format. The product must be the brightest element. No reflections on product surface.", permission:"Think Kinfolk magazine meets high-end fragrance advertising." }},
  ],
};

export const CAT_COLORS = { "Language Models":"#a78bfa", "Image Generation":"#f472b6" };
