import { C } from "./themes.js";

// ─── STANDARD SECTIONS (Language Model mode) ──────────────────────────────────
export const SECTIONS = [
  { id:"anchor",     label:"The Anchor",     number:"01", symbol:"⊕", color:C.purple,
    description:"Who is speaking.",
    prompt:"Set the role, expertise, and perspective you want the AI to inhabit.",
    placeholder:"You are a senior UX researcher with 10 years in fintech, specialising in onboarding flows for anxious first-time users…",
    tip:"The strongest prompts start here. 'You are a…' anchors everything that follows.", optional:false },
  { id:"feeling",    label:"The Feeling",    number:"02", symbol:"◎", color:C.pink,
    description:"What surrounds it.",
    prompt:"Give the context, backstory, and situation the AI needs before it can begin.",
    placeholder:"I'm building a mobile app for Gen Z users navigating financial anxiety for the first time…",
    tip:"Don't assume the AI knows what you know. Surface the details that would change the answer.", optional:false },
  { id:"voice",      label:"The Voice",      number:"03", symbol:"◈", color:C.green,
    description:"What must be done.",
    prompt:"State the task with precision. One clear action, not five vague ones.",
    placeholder:"Write three onboarding screens. Each should feel like a trusted friend talking — warm, specific, zero jargon…",
    tip:"Use action verbs. Write. Analyze. Rewrite. Compare. Generate. Vague tasks get vague results.", optional:false },
  { id:"constraint", label:"The Constraint", number:"04", symbol:"◻", color:C.orange,
    description:"The shape it must take.",
    prompt:"Define the output format — structure, length, tone, language, any rules.",
    placeholder:"Return each screen as a JSON object: { headline, subtext, cta }. Max 12 words per headline…",
    tip:"If you need JSON, say JSON. If you need a list, say a list. Format shapes thinking.", optional:false },
  { id:"permission", label:"The Permission", number:"05", symbol:"◇", color:C.blue,
    description:"What it's allowed to become.",
    prompt:"Show what good looks like. One great example is worth ten lines of description.",
    placeholder:"Here's a screen I love: 'Hey — no pressure. We're just glad you're here.' That tone. That trust…",
    tip:"Showing beats telling. Paste even one example of what you want and everything sharpens.", optional:true },
];

// ─── IMAGE SECTIONS (Image Generation mode) ───────────────────────────────────
export const IMAGE_SECTIONS = [
  { id:"anchor",     label:"The Subject",   number:"01", symbol:"⊕", color:C.purple,
    description:"What are you generating.",
    prompt:"Describe the core subject, scene type, or medium.",
    placeholder:"Cinematic portrait of a woman in her 40s, shot on 35mm film, standing in a doorway…",
    tip:"Name the output type first — portrait, landscape, product shot, illustration.", optional:true },
  { id:"feeling",    label:"The Mood",      number:"02", symbol:"◎", color:C.pink,
    description:"The emotional atmosphere.",
    prompt:"Describe the feeling, energy, and emotional register of the image.",
    placeholder:"Quiet power. The moment before something important. Melancholic but not sad…",
    tip:"Mood is the invisible layer that makes an image feel intentional rather than accidental.", optional:true },
  { id:"voice",      label:"The Scene",     number:"03", symbol:"◈", color:C.green,
    description:"The visual detail.",
    prompt:"Describe what is actually in the image — composition, lighting, colour, texture.",
    placeholder:"Golden hour light raking from the left. Shallow depth of field. Eyes sharp, background soft…",
    tip:"This is your main layer. Paint it in detail.", optional:false },
  { id:"constraint", label:"The Format",    number:"04", symbol:"◻", color:C.orange,
    description:"Technical specifications.",
    prompt:"Aspect ratio, style, rendering constraints, what to avoid.",
    placeholder:"Aspect ratio 2:3. Photorealistic. No AI smoothing on skin. No lens flare…",
    tip:"Aspect ratio, quality tags, and what NOT to include matter equally.", optional:true },
  { id:"permission", label:"The Reference", number:"05", symbol:"◇", color:C.blue,
    description:"Style and creative license.",
    prompt:"Name visual references, artists, film directors, or give creative latitude.",
    placeholder:"Reference: the visual language of Paolo Sorrentino. One unexpected lighting choice…",
    tip:"Film references, photographer names, or art movements give image AI a strong style target.", optional:true },
];
